language: python
python: "3.3"
node_js: "0.10"

services:
 - postgresql
 - memcached
 - elasticsearch

virtualenv:
  system_site_packages: true

before_install:
 - psql -c 'create database openreview;' -U postgres
 - export DJANGO_DB_USER=postgres
 - export DJANGO_LOG_LEVEL=WARNING
 - export DJANGO_FORCE_STATICFILES=1

 # Setup virtual display for in-browser testing
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"


install:
 # Upgrading nodejs..
 - sudo apt-get install python-software-properties
 - sudo add-apt-repository ppa:chris-lea/node.js -y
 - sudo apt-get update
 - sudo apt-get build-dep lxml
 - sudo apt-get install nodejs
 - sudo npm install -g bower
 - bower install
 - cat openreview/requirements/apt/{common,dev,prod}.txt | tr '\n' ' ' | xargs sudo apt-get install -y
 - pip install -r openreview/requirements/pip/dev.txt --use-mirrors
 - pip install -r openreview/requirements/pip/prod.txt --use-mirrors
 # Travis, why do you hold broken versions of psycopg2?! :-(
 - pip install psycopg2==2.5.2

script:
 - coverage run --source=openreview --omit=*/migrations/*,openreview/wsgi.py manage.py test

after_success:
 - coverage report -m
 - coveralls

branches:
  except: base-design
